[env:xiaoblesense]
platform = https://github.com/maxgerhardt/platform-nordicnrf52
board = xiaoblesense_adafruit
framework = arduino
lib_deps = 
    seeed-studio/Seeed Arduino LSM6DS3 @ ^2.0.3
lib_ldf_mode = deep+
lib_compat_mode = off
build_flags =
    -O1
    -DEIDSP_USE_CMSIS_DSP=0
    -DEI_CLASSIFIER_TFLITE_ENABLE_CMSIS_NN=0
    -O1
    -I lib/ei-model
    -I lib/Filters
    -I lib/MadgwickAHRS
    -I lib/PinchDetector
    -I lib/OrientationPointer
    -I lib/ShakeToggle
    -I lib/Haptic
    -I lib/ImuReader
    -I lib/MouseHID
    -I lib/AirMouseController
    -I include
build_src_filter =
    +<*>
    +<../lib/ei-model/edge-impulse-sdk/>
    +<../lib/ei-model/tflite-model/>
    +<../lib/ei-model/model-parameters/>