/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 11.08.2026 09:46:54

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 3360;
#else
constexpr int kTensorArenaSize = 2336;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,200 } };
const TfArray<1, float> quant0_scale = { 1, { 0.03709803894162178, } };
const TfArray<1, int> quant0_zero = { 1, { -68 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 40, 5, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 40, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 20, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 20, 1, 32, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 320, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data6[2] = { -83, 83, };
const TfArray<1, float> quant6_scale = { 1, { 0.0020831353031098843, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[2*320] = { 
  49, 55, 43, 52, 22, -6, 71, 46, 53, 84, 49, -2, -25, 8, 54, 44, 60, 61, 58, 24, 33, 61, 0, 37, -3, -6, 36, 53, 2, -18, -25, 38, 38, 65, 17, 12, -16, -9, 44, 50, 17, 25, 23, 12, -21, 4, 27, 12, 16, 17, 23, 1, 18, 39, 5, 18, -7, -7, 16, 21, -5, -16, -23, 12, 21, 41, 4, 4, -10, 7, 16, 35, 0, 3, 6, -5, 5, -1, 11, 3, -4, 1, -9, -2, -1, 30, -1, 0, 8, -11, 3, -1, 7, -7, -13, -4, 35, 28, 6, -1, -3, 2, 6, 21, -3, 3, 19, -1, -20, -6, 5, -5, -5, 17, -3, 8, -1, 23, -6, -17, -1, -12, -8, 5, 9, 13, 18, -10, 12, 21, -20, -4, -25, 0, 9, 4, -4, -3, 5, -9, -3, 7, -5, -9, -11, -3, -1, -11, -12, 9, -5, -6, -3, -1, -23, -3, 3, 68, 53, -14, 4, 14, -6, -9, -19, -3, 15, 21, -7, -10, 3, -28, 127, 7, -10, -6, -3, -11, -3, -2, -6, 21, 5, -3, 1, -32, -20, -16, 0, 78, 69, -14, 18, 29, 1, -13, -16, 0, 37, 25, -5, -3, 44, -14, 58, -6, -11, -1, -17, -5, -1, 6, -32, 17, -1, -4, 0, -14, -13, -8, 7, 35, 35, 8, 4, 37, -4, -9, -20, -5, 10, 28, 5, -2, 58, -19, 45, 6, -7, 6, 8, -6, 4, -18, -1, 12, -1, -10, -2, -5, -22, -9, 0, 12, 14, -10, 35, 33, 11, 3, -9, 8, 0, 28, -7, 11, 64, -6, 20, 6, -5, 9, 3, -8, 0, 33, -5, 1, 3, 2, 0, -23, -13, 4, 3, -4, 1, 31, 25, 32, 2, 1, 23, -3, 16, 29, 5, 18, 35, 6, 3, 5, -7, 13, 5, 5, 7, 21, -4, 17, -2, 3, -1, -4, 1, -2, 9, 5, 14, 9, 
  -39, -62, -39, -46, -20, 0, -82, -50, -59, -75, -64, -10, 17, 6, -53, -42, -55, -63, -53, -38, -22, -59, 1, -30, 4, -2, -29, -57, 1, 29, 22, -22, -35, -55, -11, -23, 11, -7, -35, -36, -21, -11, -32, -13, 16, 5, -35, -14, -8, -23, -20, -14, -15, -40, 7, -26, 2, -8, -3, -14, 1, 10, 12, -15, -18, -38, -3, -2, 6, -4, -25, -36, 3, -2, -13, -4, -12, -1, -10, -6, -1, -4, 5, 3, 0, -36, 8, -1, -11, 12, 1, 4, -9, 2, 0, 6, -26, -19, 6, 1, 13, 0, -5, -16, -2, 6, -29, 8, 12, 2, -6, -2, 4, -8, 0, 0, 13, -25, 6, 0, -6, -2, 9, 0, -1, -22, -5, 1, -16, -17, 13, 9, 27, 8, 0, -10, -5, 5, -6, 16, 13, -5, -4, 13, 3, -6, -3, 21, 16, 3, -7, 13, 6, -9, 29, -1, -1, -65, -61, 6, -12, -16, 3, 13, 13, -4, -8, -7, 3, 12, -13, 33, -126, -9, 17, 2, 14, 10, 14, 7, 11, -20, -7, 0, -6, 17, 16, 8, -3, -75, -82, -2, -19, -30, 6, 2, 25, -4, -34, -28, 1, -1, -39, 4, -56, -8, 5, 1, 10, 9, 8, 6, 22, -12, -6, 2, -8, 18, 10, 11, 3, -25, -32, -8, -3, -28, 8, -4, 15, -8, 0, -32, 0, 0, -57, 3, -46, -3, 0, -2, 1, 5, 4, 8, 13, -8, 5, 8, 3, 14, 22, 3, -7, -6, -19, 0, -34, -27, -1, -6, -4, 4, -8, -25, 7, -8, -76, 14, -10, 0, 9, -21, 0, 10, 5, -28, 7, 0, -5, 1, -1, 20, 0, 3, 2, 5, 0, -18, -21, -16, -9, -8, -14, -2, -3, -19, -5, -18, -20, 9, -8, 7, 5, -7, -6, -1, -2, -29, 6, -9, 5, -10, 6, -11, -10, -11, 9, -11, -7, -20, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 2,320 } };
const TfArray<1, float> quant7_scale = { 1, { 0.015046084299683571, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[32] = { -1339, -1465, -139, -64, 94, -66, -784, -1286, -35, -247, -1032, 45, 321, -80, -196, 141, -81, -217, -121, -100, 214, -1210, -337, -352, -335, 90, 79, 1, -138, 308, 338, -156, };
const TfArray<1, int> tensor_dimension8 = { 1, { 32 } };
const TfArray<32, float> quant8_scale = { 32, { 0.00026354994042776525, 0.00025827527861110866, 0.00029057066421955824, 0.00036996777635067701, 0.0003453223907854408, 0.00010093692253576592, 0.00025602692039683461, 0.00027076355763711035, 0.00049031537491828203, 0.00033523829188197851, 0.00028541841311380267, 0.00034208182478323579, 0.00057644618209451437, 0.00010520064097363502, 0.00038713109097443521, 0.00024298315111082047, 0.00052952120313420892, 0.00043815598473884165, 0.00050339027075096965, 0.00038735184352844954, 0.00030437999521382153, 0.00025515197194181383, 0.0001037932452163659, 0.00024881408899091184, 0.00011707464727805927, 0.0003197019686922431, 0.00041333885747008026, 0.0004324347828514874, 0.00010511556320125237, 0.00051806616829708219, 0.00043651860323734581, 0.00031197007047012448, } };
const TfArray<32, int> quant8_zero = { 32, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[32*1*3*16] = { 
  /* [0][0][][] */ 70,127,-82,16,26,33,8,52,25,-9,-88,31,28,85,25,-52, -1,61,-125,56,25,61,112,23,-33,-64,-55,39,45,13,-63,-47, 72,92,-81,89,71,-9,21,34,50,-52,-22,59,25,15,31,-38, 
  /* [1][0][][] */ 33,88,-64,5,43,23,127,58,81,12,-47,23,35,63,-29,22, 34,92,-95,37,84,10,52,-21,-4,40,9,7,-5,18,16,-8, -1,107,-69,2,-2,56,-34,5,-4,1,-88,62,43,86,14,-45, 
  /* [2][0][][] */ 17,20,21,45,78,127,12,21,-91,115,-64,122,57,28,-26,53, 22,49,25,16,42,106,32,33,9,94,-85,-22,19,83,104,42, -5,-9,-44,-19,56,-15,-15,70,5,69,0,10,19,41,103,69, 
  /* [3][0][][] */ 68,53,55,26,76,54,14,38,-52,80,-27,116,86,73,44,3, 11,-4,-29,26,35,73,-13,72,51,127,28,41,4,8,41,8, -44,47,26,-2,41,30,83,-13,67,24,-2,15,-18,26,12,2, 
  /* [4][0][][] */ -43,-99,-22,19,-120,-29,-17,12,17,101,-75,25,-34,-27,55,68, 12,-31,-13,-20,34,29,59,54,30,73,-17,58,12,-34,48,-11, 3,-79,47,-47,32,34,96,47,25,127,50,52,57,14,37,-38, 
  /* [5][0][][] */ -97,68,-24,-58,-104,-41,93,-108,-81,64,4,-85,-39,-5,61,-55, -109,16,78,92,58,-21,-127,27,30,-103,-118,-33,16,-87,26,25, 46,-64,-37,-92,15,-46,100,-27,-107,-57,-37,127,0,-88,-124,-55, 
  /* [6][0][][] */ 94,97,-85,18,81,67,38,1,1,-69,-23,-41,-29,82,-53,-73, 101,42,-12,17,108,81,61,51,61,5,-11,-44,73,9,31,-59, -1,127,-66,-15,111,14,50,-66,-14,-80,-40,-88,-40,72,15,-61, 
  /* [7][0][][] */ 39,76,-127,60,61,73,76,38,15,-39,-13,32,34,39,37,-3, 15,74,-99,28,19,24,33,-32,-12,21,-29,-10,-10,9,42,-57, 28,91,-102,56,83,25,63,-20,39,-23,-91,71,35,73,-21,-22, 
  /* [8][0][][] */ 72,66,22,37,127,66,53,5,3,111,-1,48,66,74,29,2, 32,31,9,-23,106,31,58,47,22,55,19,9,49,25,56,-28, 8,-5,-2,-1,19,-8,9,9,-20,-45,-26,17,10,-17,47,-13, 
  /* [9][0][][] */ 62,82,-6,75,76,71,63,37,-3,127,-18,70,43,33,-11,-5, 30,105,0,-18,105,124,61,46,0,106,35,-21,39,36,-9,-71, 28,41,26,-28,57,82,16,-50,-21,-80,23,-53,-14,-8,0,-21, 
  /* [10][0][][] */ 25,28,-45,73,-34,-2,-18,23,-56,-3,-127,9,45,60,34,72, 65,62,-61,68,53,-36,45,-8,8,-27,-44,60,-38,72,-4,-19, -5,34,-58,81,19,-1,3,58,-49,-86,-71,58,-40,94,-81,48, 
  /* [11][0][][] */ -39,-69,41,11,-56,-15,27,23,1,56,-104,17,52,36,70,66, -53,-72,-13,-44,33,-4,-9,20,49,127,53,-6,10,-13,33,-56, -38,-102,-21,-31,63,1,97,-2,18,-22,16,-1,-38,-61,40,-6, 
  /* [12][0][][] */ -25,-16,13,21,-93,-58,-118,-45,-33,-75,12,-41,-26,-24,-32,32, -4,-28,11,6,-71,-14,-68,-21,-65,-77,3,-40,-26,-9,-67,29, 42,50,33,52,-25,33,-68,3,-96,-97,5,17,1,58,-127,9, 
  /* [13][0][][] */ 10,-35,-120,-69,74,-62,-121,-70,-57,107,86,-88,-27,0,80,9, -48,-123,-109,68,-69,68,60,39,-21,-127,-89,-126,19,34,82,-92, -77,-47,-7,-38,78,-71,-77,-72,-79,59,-44,53,-55,-32,14,96, 
  /* [14][0][][] */ 55,50,-1,40,63,75,44,91,75,102,2,78,102,36,42,-3, 19,16,12,28,31,8,48,0,93,94,12,0,2,-19,127,-21, -19,-16,-12,-34,24,-47,72,-48,69,-85,24,-57,-23,5,76,-19, 
  /* [15][0][][] */ 43,74,17,4,-34,75,-20,-35,-114,16,-105,-2,16,61,-41,40, 4,80,-15,74,69,87,75,21,-61,68,-71,115,46,110,28,58, 50,81,-30,32,12,33,38,94,65,116,57,79,-26,100,56,127, 
  /* [16][0][][] */ 12,37,18,38,91,69,44,7,20,127,5,70,36,61,-5,-27, 28,29,5,-5,96,76,66,-10,16,14,27,-7,22,17,11,-38, 19,18,-1,27,-22,3,-6,46,-27,-9,-7,54,13,2,28,-4, 
  /* [17][0][][] */ 81,31,3,54,82,56,43,70,34,42,-10,60,77,59,24,6, 46,20,1,-17,127,4,68,4,39,23,44,-23,-3,33,62,-31, -15,32,-23,-24,60,0,8,-1,7,-66,43,-26,-13,21,9,-28, 
  /* [18][0][][] */ 41,28,8,49,127,84,12,56,11,98,6,69,59,54,29,17, 52,16,2,-13,97,66,43,18,37,65,29,6,43,42,44,2, -29,20,-21,-32,-7,-6,47,19,24,-23,-29,6,2,-3,11,-18, 
  /* [19][0][][] */ -57,-28,-21,46,-123,39,-73,-12,-73,15,-94,-19,-31,16,-56,43, 13,-14,32,78,10,57,9,56,15,86,-53,63,27,23,2,53, 8,-16,-6,15,127,30,3,45,16,90,53,47,31,42,68,-8, 
  /* [20][0][][] */ -45,-57,-6,-42,118,19,120,-33,67,40,82,-5,-41,-4,4,-114, 54,-33,83,14,20,32,59,13,-23,2,-105,-13,17,4,48,43, 45,-62,20,54,-99,-29,4,48,65,50,-127,60,21,-29,90,53, 
  /* [21][0][][] */ 77,94,-112,46,75,20,70,-19,88,-36,-19,40,58,2,7,-113, 66,83,-33,62,115,70,85,6,61,-20,11,7,27,37,2,-53, 80,127,-46,14,69,0,31,10,-14,25,-46,40,54,51,-39,-91, 
  /* [22][0][][] */ -12,68,-61,12,-94,-118,-18,59,-127,77,-13,-98,-46,-55,21,-78, -30,-122,58,17,111,-85,10,111,-69,-103,16,-104,-24,-103,19,86, -34,104,-86,-64,-110,-105,-105,-22,-67,94,-15,-88,-103,-10,80,-43, 
  /* [23][0][][] */ 30,-89,66,58,52,97,7,76,-71,68,-99,108,80,-27,25,47, 26,55,25,39,10,36,-90,94,-28,127,-109,51,6,34,98,30, -55,-40,-6,-52,51,-81,26,27,45,6,39,-67,42,-96,89,-35, 
  /* [24][0][][] */ -102,62,-43,48,-101,54,-44,84,-71,47,2,-31,-127,-14,-121,-62, 50,-11,28,24,-105,-1,21,29,-113,-77,12,-42,-74,-65,-93,34, 42,11,-120,-91,-88,-71,41,-97,22,52,65,-43,53,49,-87,9, 
  /* [25][0][][] */ -12,-17,39,38,-17,-36,15,44,14,127,16,81,65,-23,86,63, -39,-99,9,-85,63,2,40,-31,85,61,43,18,-14,-38,23,-14, 11,-46,46,-71,33,-53,36,8,13,-34,-11,61,-56,-73,20,-88, 
  /* [26][0][][] */ -9,-15,24,16,-127,-6,-59,32,-10,66,-94,81,32,29,65,67, -23,-34,-22,17,59,15,13,7,53,105,-16,25,40,-29,76,-12, -8,-33,-10,-97,61,-1,72,-36,61,16,55,-55,1,-35,16,-51, 
  /* [27][0][][] */ 35,11,39,26,40,38,1,51,15,127,-26,72,57,37,15,0, 6,-1,-3,-24,72,28,33,-30,42,102,31,-4,4,14,45,-36, -50,6,13,-5,26,-4,71,-18,5,-40,21,5,11,-10,48,-20, 
  /* [28][0][][] */ 48,112,-29,-29,-28,-60,60,-50,54,28,-124,52,-87,-43,53,27, -8,-36,-94,-48,38,-20,-70,83,-123,-107,-2,-10,-76,44,-14,-117, -29,-11,-104,-40,16,-29,36,37,-75,78,26,-114,69,-8,-127,96, 
  /* [29][0][][] */ 48,16,35,-51,-40,8,-84,-72,-28,-127,14,-88,6,-34,-47,-3, 42,5,43,-16,-72,-7,-85,-35,-15,-72,28,-110,15,-27,-28,-5, 68,30,18,-51,5,55,-34,-50,21,-59,42,-84,-11,-64,-17,2, 
  /* [30][0][][] */ 23,-10,36,-52,-38,-8,-53,-84,-65,-120,-5,-127,-20,-40,-13,-9, 37,30,8,-31,-48,-20,-77,-35,-26,-116,35,-127,-6,-70,-56,9, 58,11,26,-68,11,50,-47,-77,-1,-45,58,-85,37,-90,-55,9, 
  /* [31][0][][] */ 20,58,-37,82,-76,37,-91,27,-127,-6,-72,-38,6,41,-15,37, -36,19,32,76,34,3,59,37,-46,91,-83,89,38,67,-19,29, 7,-3,3,42,106,17,64,16,-49,121,-18,29,12,34,26,82, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 32,1,3,16 } };
const TfArray<32, float> quant9_scale = { 32, { 0.0041085323318839073, 0.0040263044647872448, 0.0045297634787857533, 0.0057675009593367577, 0.0053832991980016232, 0.0015735257184132934, 0.0039912546053528786, 0.0042209867388010025, 0.0076436237432062626, 0.0052260961383581161, 0.0044494443573057652, 0.0053327814675867558, 0.0089863333851099014, 0.0016399936284869909, 0.0060350634157657623, 0.0037879124283790588, 0.00825481116771698, 0.0068305004388093948, 0.0078474506735801697, 0.0060385046526789665, 0.004745040088891983, 0.0039776144549250603, 0.0016180535312741995, 0.0038788123056292534, 0.0018250999273732305, 0.0049838973209261894, 0.0064436215907335281, 0.0067413114011287689, 0.0016386673087254167, 0.0080762365832924843, 0.0068049752153456211, 0.0048633632250130177, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[16] = { -537, -1897, 2122, 51, 17, -150, -21, 30, 43, 35, 1122, 58, -126, 79, 95, 1139, };
const TfArray<1, int> tensor_dimension10 = { 1, { 16 } };
const TfArray<16, float> quant10_scale = { 16, { 0.00020008116553071886, 0.00014514948998112231, 0.00014354391896631569, 0.00031961104832589626, 0.00031143624801188707, 0.00023978382523637265, 0.00028336170362308621, 0.00017128291074186563, 0.00023933565535116941, 0.00035711060627363622, 0.00025095869204960763, 0.00022077743778936565, 0.00019031064584851265, 0.00021257801563479006, 0.0002252887497888878, 0.00018555315909907222, } };
const TfArray<16, int> quant10_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[16*1*3*5] = { 
  /* [0][0][][] */ 33,31,-127,57,-55, 45,76,-111,14,-41, 38,48,-24,20,-27, 
  /* [1][0][][] */ -20,20,-127,-94,14, 35,96,66,-81,98, 89,65,-2,-68,-6, 
  /* [2][0][][] */ 18,-68,-24,1,-54, 6,41,-6,10,127, 46,0,29,-89,18, 
  /* [3][0][][] */ 9,8,72,127,38, 41,4,21,126,20, 58,36,16,95,30, 
  /* [4][0][][] */ 123,12,-53,-124,25, 40,21,-77,-127,0, 22,-39,-81,-56,43, 
  /* [5][0][][] */ 21,22,40,-127,48, 15,36,-42,-121,53, -2,67,-47,-30,-3, 
  /* [6][0][][] */ 102,8,14,-127,-101, 47,-20,5,-106,-28, 29,-9,20,42,9, 
  /* [7][0][][] */ 109,78,106,66,-53, 127,46,59,73,-87, 52,-90,114,-19,43, 
  /* [8][0][][] */ 70,-17,64,19,-84, 7,-63,40,-47,-127, 40,6,-6,-73,-120, 
  /* [9][0][][] */ -13,20,78,88,-68, -2,-28,49,-66,7, -3,7,-26,-127,19, 
  /* [10][0][][] */ 26,4,-66,-74,-42, -59,-43,-43,-127,-21, -37,8,-117,-97,-68, 
  /* [11][0][][] */ 49,-117,27,119,-98, 51,23,72,51,-1, 127,61,100,-73,31, 
  /* [12][0][][] */ 14,127,39,101,0, 80,75,76,-12,-89, -1,-6,-4,-35,-76, 
  /* [13][0][][] */ 82,48,22,86,114, 108,56,8,126,116, 43,-40,-23,127,84, 
  /* [14][0][][] */ 80,8,8,94,-115, 32,-40,20,127,-111, 50,-3,32,-18,-124, 
  /* [15][0][][] */ -54,29,53,118,-83, -89,-61,66,127,-49, 8,-16,18,61,41, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 16,1,3,5 } };
const TfArray<16, float> quant11_scale = { 16, { 0.005393308587372303, 0.0039125918410718441, 0.0038693128153681755, 0.008615308441221714, 0.0083949519321322441, 0.0064635174348950386, 0.0076381852850317955, 0.0046170339919626713, 0.0064514367841184139, 0.0096261315047740936, 0.0067647430114448071, 0.0059511889703571796, 0.0051299380138516426, 0.0057301684282720089, 0.0060727940872311592, 0.0050016972236335278, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,40,5 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,40,16 } };
const TfArray<1, float> quant13_scale = { 1, { 0.0641469806432724, } };
const TfArray<1, int> quant13_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&quant13_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,40,1,16 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,20,1,16 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,20,16 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,20,32 } };
const TfArray<1, float> quant17_scale = { 1, { 0.13845032453536987, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,20,1,32 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,10,1,32 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,320 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,2 } };
const TfArray<1, float> quant21_scale = { 1, { 3.5686435699462891, } };
const TfArray<1, int> quant21_zero = { 1, { -1 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfArray<1, float> quant22_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant22 = { (TfLiteFloatArray*)&quant22_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 208), (TfLiteIntArray*)&g0::tensor_dimension0, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 640, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 128, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 1536, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 240, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 640), (TfLiteIntArray*)&g0::tensor_dimension13, 640, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 640, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 640), (TfLiteIntArray*)&g0::tensor_dimension15, 320, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 320, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 640), (TfLiteIntArray*)&g0::tensor_dimension17, 640, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 640, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 640), (TfLiteIntArray*)&g0::tensor_dimension19, 320, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 320, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 320), (TfLiteIntArray*)&g0::tensor_dimension21, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1084395_4_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1084395_4_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1084395_4_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1084395_4_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1084395_4_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
