/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 22.06.2026 18:31:28

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1552;
#else
constexpr int kTensorArenaSize = 528;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,185 } };
const TfArray<1, float> quant0_scale = { 1, { 0.14593884348869324, } };
const TfArray<1, int> quant0_zero = { 1, { -43 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[3] = { -1399, 1144, 124, };
const TfArray<1, int> tensor_dimension1 = { 1, { 3 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00033445979352109134, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[3*10] = { 
  54, -60, 123, -102, -53, 20, 93, -83, -127, 95, 
  73, 111, -53, -78, -108, 45, 24, -98, -6, -49, 
  -94, -23, 72, 27, -56, -76, -120, -30, 98, 19, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 3,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0069040847010910511, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { 240, 2274, -968, 478, -1139, -52, 69, 110, 416, -97, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.00022619258379563689, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  45, -53, -46, 11, 67, 10, 76, -73, -4, -30, 16, 13, 43, 78, 68, -56, 56, -18, -42, 15, 
  -45, -78, 46, 57, 37, -27, -32, -60, -63, 24, -35, -36, 43, 85, 58, 61, -33, 23, -16, -62, 
  -59, -66, -2, 64, -34, -41, -26, 11, -28, -10, 21, 35, -15, -16, -4, -48, 80, -66, -60, -45, 
  14, 9, 64, 0, -44, 53, -38, -30, -19, 77, 69, 33, -50, -49, -27, -31, -39, -37, 122, 66, 
  -43, 41, -66, -31, -60, 46, -28, 14, -63, 20, 60, 39, -14, 12, 3, -65, -46, 69, 42, 51, 
  -61, 48, -47, 34, -22, -80, -7, 51, -79, -37, 52, 41, -35, 39, -28, -46, -26, 42, -47, -5, 
  85, 32, -40, -53, 53, 53, 5, -24, -18, -2, 42, 28, -49, -26, 37, -12, 74, -12, -16, 6, 
  -31, 62, 32, 39, -8, 59, 60, -82, 78, -16, -40, 77, 45, -15, -100, 34, 0, 4, 62, 68, 
  -6, 28, 37, 23, 61, 24, -73, -18, -20, 36, 66, 15, -3, -79, -40, 65, -62, 48, -22, -34, 
  60, -49, -11, -5, 53, 67, -16, 4, 53, -127, -42, 33, -51, -11, 48, -13, -22, 61, -37, 83, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0056078555062413216, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { -84, 0, 0, -8, -7, -10, -12, -20, -1, 79, -7, 0, 0, -21, -38, 0, -61, 0, 52, 15, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.00097901630215346813, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*185] = { 
  -26, 31, 8, 7, -4, 6, 0, -23, 0, -27, -6, 4, -26, -18, -7, 20, 5, 18, -14, -15, 21, -7, 23, 4, -23, 17, -13, -13, -18, -21, 5, 7, 14, -21, -23, 9, -13, -19, -14, -5, 5, -1, -46, -34, -43, 1, -20, 3, -35, -34, -19, -37, -6, -18, -33, 6, 11, 9, 13, 5, -2, -18, -7, -26, -12, -26, -7, -3, 13, -12, -3, -29, -24, -16, -35, -6, 5, 5, -1, 27, 12, 3, -1, 12, 0, 8, -19, 3, -13, -17, 15, 1, -5, 28, 4, -16, 31, 21, -11, -2, 6, -18, 13, 21, 1, -2, -2, 9, -6, -4, 28, 5, 37, 18, -25, 11, -1, 18, -14, 19, 23, 11, 16, 34, -14, 7, 26, 13, 31, 7, -10, -3, 34, 19, 31, -2, 13, 36, 6, 12, 23, 11, -5, -5, 2, 6, 5, 24, -29, -24, -16, 3, -16, 23, 14, -3, 27, 14, -16, 8, 18, 28, -5, -1, 0, -2, -9, -9, 24, 30, -4, 4, 3, 2, 5, 28, 23, 22, -7, -9, 12, 18, -13, -7, 11, 
  -25, -2, 21, 3, -7, 4, 8, 8, 11, 23, -16, 10, 3, 5, 15, -13, 20, 12, 25, -15, -4, -2, 21, -5, 13, 12, -4, 18, -6, -18, -4, 23, 22, 24, 17, -8, -20, -2, 7, -11, -10, -14, 24, 18, 14, -7, 19, -17, 2, 0, -23, -3, 1, -9, -3, -25, -24, 20, 21, -20, -4, 17, -10, -4, -6, 0, 19, -25, 14, -7, 23, -14, 15, -2, 4, 21, -8, -14, -2, 22, -3, -25, -13, 0, 11, 2, -5, -18, 5, -6, 8, 8, 23, 6, 1, 14, -12, -21, 4, -22, 5, 24, 0, -4, -17, 12, 18, -16, -5, -5, -7, -22, 25, 7, -7, 22, 6, 5, -19, -18, 6, -24, -8, -13, 12, -2, -1, 10, -21, 23, -9, -7, 16, -8, 24, 15, -16, -8, -4, 16, -24, 4, -3, -11, 1, 16, 16, 12, -10, -15, -12, -9, -11, -10, -10, 18, 15, 23, -17, -12, -15, -20, 14, -11, -21, -8, -19, 4, -22, -6, -5, -16, 11, -9, -4, 16, 13, -8, -14, -15, -19, 6, 9, 8, -6, 
  16, -3, -22, -18, 11, -13, 15, 21, 24, -2, -19, 4, -18, 12, -15, 18, 8, 15, 0, 11, 25, -23, 14, -20, 3, -6, 24, 12, -13, -20, -13, 17, 13, -18, -5, -8, -22, -2, 15, -19, 13, 13, -23, -4, 9, -5, -13, -20, 9, -7, 13, -6, -5, 0, 13, -21, 3, 3, 3, -7, 23, -9, -4, 4, -7, 15, 5, -14, -8, -8, -1, -25, 2, 21, -4, -22, -21, 14, -12, -15, 10, -14, 9, -1, 2, 4, -6, 0, -20, 0, -18, 21, 6, -9, 25, 17, 8, 13, 9, 7, -24, -22, -13, -18, 11, -10, 22, 18, 2, -4, -12, 13, 2, -20, -16, -21, 12, 25, -6, 11, -13, 20, 25, -24, 22, 21, 7, 17, -21, -1, 14, -15, 5, 12, 13, 12, -12, 18, 15, 9, -4, 22, 23, 23, -20, 0, -21, 2, -9, 3, 11, -13, -9, 3, 10, 25, 14, -8, 20, -19, 2, 18, 6, 22, -1, -15, -11, -4, -9, -4, -20, -7, 1, -24, -8, 4, 15, -12, -13, -22, 15, -20, 0, 23, -14, 
  -20, 11, -15, 14, -3, 17, 0, 27, 15, -19, 23, 22, 14, 18, 13, -3, -17, -10, 11, 18, -14, 12, -14, -7, 17, 15, -16, 17, 23, 18, -9, 12, 23, -9, 17, 5, 27, -23, 2, 18, -22, 14, 3, 23, 28, -17, 2, -13, 18, 15, -13, 2, -2, -22, 9, -17, -19, -22, -8, 0, 25, 11, 26, 20, -14, -20, 17, -19, -14, -21, 17, -11, -11, -16, 4, 7, -9, 24, 7, 25, 6, 17, 19, -6, -3, -19, -1, -9, 16, -9, 11, 10, -20, 4, 22, -9, -14, -4, 21, -5, -7, -1, 21, -14, -11, 0, 4, -6, 6, 8, -20, 4, -1, 18, 0, 20, -21, 3, 19, 0, -22, 22, 3, 10, -19, 3, 1, -14, 8, 9, -8, -21, -5, 23, -4, -11, -15, 7, 4, 19, 17, 18, 8, -8, 6, 7, -9, -16, -9, -20, -9, -17, 19, 24, -15, 10, 11, 26, -12, -20, -7, 13, 22, 17, -12, 8, -7, -16, 11, 5, -22, -10, 1, -21, 16, 12, 10, 13, 19, -24, -5, 19, 23, 21, 1, 
  20, 5, 3, -17, -21, -18, 22, -5, -11, 16, -6, 6, -15, -10, -16, 15, 16, 18, -1, -5, -2, 24, -4, -3, -7, 2, 19, 18, -22, -19, 12, -15, 23, -17, -7, -11, -7, -24, 5, 14, 1, 7, -21, -8, 15, -15, 19, 16, -4, 18, 17, 19, -19, -5, -6, 25, 17, 20, 23, 16, -21, -19, 24, 24, 2, 15, -10, 26, -24, -5, -21, 8, 18, 10, 9, 12, -9, -8, -13, -9, 20, -23, 13, -17, 9, -14, 6, -17, 18, -8, -8, 2, 7, 17, 8, 2, 6, -5, -18, -19, -5, -21, 7, -6, 24, -12, -23, -5, -16, 9, -15, -2, -15, -2, 8, -3, -9, -16, -13, -2, 24, -6, -14, -2, -21, 3, 25, -19, -11, 11, -7, -3, 11, -4, -5, -5, 14, 14, -22, 19, 9, 5, 17, 3, 18, -23, 20, 5, -23, -23, -4, 11, -10, -16, 12, 26, 21, -13, 23, -18, -9, 17, -22, -5, -23, -16, 6, -8, 24, -7, -6, -23, -19, 15, 14, 4, -9, 14, -7, 9, -10, 3, 9, 9, 7, 
  -9, 19, 5, -3, -10, -18, 4, 27, -8, 7, -22, -8, -23, 13, 6, 1, -21, 9, -6, 4, -18, -19, -1, -11, 20, -5, 8, -2, -10, 26, -3, -1, 21, -14, 7, -22, 19, -16, 9, 20, 16, 8, -16, -5, 6, -23, -17, -15, 1, 17, 24, -2, 10, -9, 13, 16, 10, -2, 16, 3, 8, -23, 18, -18, -6, 1, -8, 22, 23, 13, 25, -10, 19, -17, -27, -17, -4, -5, 15, 2, -18, 11, -11, 21, -1, -18, 9, 0, 26, -3, 5, 3, -14, 21, 3, -1, -2, 10, 1, 17, -2, 9, 22, -13, 7, 6, 26, -15, 10, 15, -1, -4, 8, 13, 16, 3, 14, -18, 8, -14, -23, 15, -18, 5, 3, 25, -3, -8, -11, -21, 3, 10, -14, -7, 7, 24, 13, -18, 21, 25, 15, 1, 2, -13, 5, -13, 24, 25, 20, -13, 18, 5, 7, -21, 19, 0, -6, 21, -8, 0, 16, -23, 14, -19, 18, -23, 26, -12, 15, 4, 0, 22, -20, 2, -19, 8, -18, -6, 26, 14, 23, 10, -23, -18, -2, 
  10, -5, -10, -15, -17, -24, -7, 19, -8, 3, 0, -1, 2, 16, 11, -3, -9, -12, 26, 21, -11, 6, -10, 18, -9, -1, 27, -19, 22, 8, 18, -22, 2, -2, -18, 16, -21, 9, -18, 24, -4, 5, 0, 3, -11, -20, 26, -12, -1, -4, -15, 22, -20, 17, 10, -1, 4, 22, 15, -8, -14, 4, 20, -14, 14, 8, -21, 17, -17, -12, 6, 24, -6, 13, 6, 19, 9, 19, 12, -9, 21, 17, 3, 9, -13, -6, 17, 8, -10, -9, -17, 17, -8, 25, -6, -23, -10, -13, -21, -1, -13, -13, 3, -5, 26, -2, -2, -15, -12, 1, 1, 12, 18, -25, 5, -6, 15, -8, -20, -7, -12, 7, -20, 1, -8, -19, -1, 12, -5, -20, 12, -22, -1, 14, 18, 21, -19, 13, 19, 27, 11, 16, -8, -24, -17, 4, 19, -21, 17, 15, -17, 19, -3, 23, -9, -22, 6, -9, 18, -11, 25, 10, -4, -16, 17, -9, -9, 15, 19, 6, -23, 19, 17, 27, 13, -19, -23, -9, 11, -4, 19, -7, 23, 3, -9, 
  16, -24, 5, 18, 18, 10, 10, 13, -5, 24, -3, 27, -6, 13, -14, -21, -6, -11, -14, 26, 24, -13, -11, 2, -3, 27, -4, 9, -21, -1, 8, 26, 8, -19, -6, -21, -2, 3, 16, -10, -7, 5, 28, 26, 11, 0, 7, -19, -13, 14, -15, -5, -3, 6, -6, -14, -20, 20, 19, -22, -15, -6, 15, -16, 16, 9, 8, -8, -9, 28, -13, 7, -2, 13, -3, 6, -11, 11, -18, 15, 27, -23, 17, 2, 9, -21, 14, 14, 20, -6, -3, -19, 6, -12, -18, -8, -6, -19, 4, 25, -6, 17, 1, -20, -1, -7, -9, -20, 26, -7, -12, -23, 5, 9, 18, -14, 22, -1, -7, 12, -6, 9, 0, -18, 12, 13, -14, -18, -2, -1, 18, 1, -3, 7, -14, 18, -2, -3, 4, 0, -1, 17, 17, 23, 12, 18, 2, -16, 14, 2, 11, -14, -1, 17, 18, 10, -7, 6, -2, -5, 0, -18, 9, -2, -2, -6, -22, 12, -21, -3, 18, -6, -7, 5, -19, 17, -10, -22, -10, -1, 1, 23, -5, -11, -16, 
  14, 24, 14, -4, -22, 16, -2, -14, -2, -3, 2, 16, 15, -9, 5, -10, 11, -11, 25, 6, 24, 18, 23, 11, 16, 17, 19, -2, 21, -21, 15, -23, -3, 0, -20, -7, -21, 21, -17, 2, -13, -13, -22, -9, -22, 8, -8, -3, -13, 8, -23, -24, 25, -15, 13, 12, 4, 12, -2, -9, 17, -5, 22, -10, 2, -24, 22, 19, 16, -12, -10, -7, 5, -20, -8, -23, -19, -12, -15, 22, -12, -14, -19, -11, 22, 6, -1, 9, 15, 14, 0, -22, -22, -5, 20, -1, 23, 6, 12, -14, -17, -15, -11, 12, 3, 19, -6, 3, 7, -2, -11, 17, 4, 11, 19, 23, 9, -16, 21, -6, 18, 20, 2, -7, 14, -23, 5, 25, -22, 19, -23, 20, -25, -7, -17, 0, -18, 23, 7, 22, 22, -1, 18, -13, -20, 4, 11, -17, -23, -15, 22, 14, -14, -17, -12, 15, -24, -23, 14, -4, 15, 3, 4, -20, -6, -23, -21, 8, 6, 6, 22, -3, 4, 20, 22, -10, 20, -7, -25, 10, -21, -8, -18, -8, 1, 
  37, -10, -5, 3, -18, 23, -14, 8, -9, -18, -11, -10, -25, -1, -7, 29, 7, 24, 23, -10, 1, 17, 6, 28, 29, 18, 2, 12, 4, 15, -6, -1, -14, 2, 19, 10, 20, 41, -54, 9, 3, -2, -12, 4, -5, -22, 14, 17, 43, -9, 22, 33, -18, -14, -11, 3, 14, 4, -20, 15, -15, -5, -14, 20, 2, -5, -27, -7, -19, 8, -15, 16, 19, -3, 18, -127, 68, -10, -43, -3, -11, 17, -20, -18, -12, 30, -11, -10, 11, 5, 19, 3, -18, -15, -10, 12, -11, -34, -32, -19, 7, -26, -29, -21, -9, -12, -34, -21, -5, -3, 1, 7, -39, -27, 16, -6, 13, 3, 9, 7, 18, -35, -8, 25, -15, 16, 15, -9, -16, 4, -19, -23, -17, -14, -30, 3, 15, -7, -3, -29, 10, -26, 2, -8, -6, 0, 16, -12, 17, -7, -88, -12, -6, -17, 35, -15, -12, 12, -15, -4, -7, -25, 12, 13, 2, -23, -12, -13, -2, -16, 3, 13, 13, -12, -25, -18, -2, -16, 18, -6, -28, -2, 14, 16, -2, 
  23, 6, 11, -25, -21, -9, 16, 5, -1, 10, -18, 9, 8, -19, 13, -14, 1, 1, 10, 7, -20, 13, -22, 21, 22, -3, -11, -7, 19, 18, -23, -19, -19, -4, 26, 23, -6, -21, -20, 7, 8, -5, 2, -7, -7, 19, 3, -23, 16, 11, -7, -15, -4, -1, 19, 23, -15, -10, 7, -3, 8, 10, 17, 18, 7, -23, -22, 12, 12, 8, 21, 4, -5, -9, -1, 23, 6, -17, 10, 26, -10, -16, 9, -16, -10, 18, -8, 8, -8, -12, 1, 25, 13, -12, -3, 3, -13, 10, -21, 13, 22, 17, 13, 12, 13, -11, 2, -22, 20, 3, -5, 0, 9, 11, -26, 2, -6, 22, -8, -13, -11, -20, -14, -18, 22, 13, -17, 7, 13, -22, 17, -10, -18, -23, 9, 9, -2, -22, 24, 16, -9, -17, -10, 8, -3, -23, -2, -8, 9, -11, -2, 12, 11, 23, -13, -13, -9, 4, -3, 2, 21, -21, 20, 10, -1, 3, 7, -14, -1, 3, 17, -8, -12, -22, 20, 22, 9, 2, 10, 24, 8, -21, 12, -19, -4, 
  -3, 9, 22, -8, -19, -23, 25, -10, 19, -6, 22, 23, 16, 23, -9, 11, -10, -9, 23, 1, -6, -5, 24, 1, 8, 10, 16, 12, 25, 10, -2, -5, 1, -10, 7, -6, -18, 6, 7, 13, 11, 18, 22, -4, -13, -8, 6, 12, -22, -2, -19, 17, 8, 9, 23, 15, 13, -5, 3, -20, 19, 14, -1, -7, 18, 15, 16, -6, -5, -6, -20, 1, -14, -15, 20, 7, 11, 20, 11, 4, 11, 23, -21, -14, -24, -23, -16, 12, -3, 16, 13, -20, -25, -19, 5, 7, 11, 17, -4, -7, -3, -2, 19, 18, 16, 10, 2, 25, 0, -21, -5, 5, 10, 8, -23, -16, -23, 2, 16, 9, 25, 23, 2, -5, -2, -7, -13, -19, 25, 19, -15, 15, 10, -5, -22, 5, -19, 19, -12, 14, -2, 3, -4, 11, 17, -23, 1, -10, -17, -13, 18, -14, -3, 2, -4, 9, 12, 25, -2, -6, 23, -7, 2, 13, -22, 11, -10, -15, 16, 5, 9, 2, 21, -11, 22, 0, 24, 25, -5, 21, -9, 22, 12, 18, -17, 
  -12, -24, 0, -8, 15, -22, -15, -25, -20, 12, -6, -23, 6, 13, -9, 19, 3, -9, 21, -7, 12, 14, -16, 16, 13, -8, 2, -12, 21, -7, -11, 6, -24, 23, 16, 16, 20, -17, -21, -16, -3, 4, -20, -12, -25, -10, 23, 14, -4, 25, 17, -22, -25, 5, -17, -25, -17, 8, -5, 11, -8, -18, -19, 17, 4, 6, 17, 10, 2, 17, 0, -12, 11, 16, 7, -25, -10, 19, -22, -22, 4, 11, 21, 16, 23, 19, -23, -15, 1, 15, -18, 23, 5, 4, -17, -23, 9, 2, 16, -6, -17, 15, 12, 8, -1, -21, -2, 20, 13, 4, -1, -8, 1, -12, -17, 4, -12, -8, 22, 13, 14, -3, 9, -14, 8, 10, -25, 14, -14, 21, -2, 13, 20, -2, 8, 23, 14, -1, 20, 25, 16, 5, 20, -6, -10, -7, -25, 18, -8, -25, 6, -18, -1, 8, -2, 24, -18, 14, -9, -12, 18, -8, -25, -10, -18, -25, -1, 25, -11, -14, 22, -16, -23, 9, 11, 15, -11, 5, -12, -25, -20, -6, -9, -4, 19, 
  -22, -23, 0, -5, 16, 24, -22, 23, 0, 7, 3, 6, 27, 6, -8, -21, -29, -7, -20, -10, -20, -17, 1, -8, -10, -21, -13, 22, -4, 2, 7, -26, -18, -23, -1, 8, 10, -3, 49, 26, 25, 15, 36, 3, 36, -4, 12, 23, 24, 20, 17, 18, -10, -9, 28, 0, 14, 26, 20, 0, 4, -5, 1, -13, 22, 26, 30, 28, 13, 32, -14, 4, 26, 6, 12, 39, -17, -9, 22, -3, 4, 12, -10, -4, 10, -3, 15, 20, 0, -26, 2, 9, -10, 21, -16, -12, -6, 30, 8, -9, 10, 27, 10, -12, -8, 17, 4, 2, 3, 17, 20, -42, 4, 40, -16, 19, 10, -21, 10, -24, -5, -8, -19, -18, 20, -1, -22, 16, 5, 18, -21, -21, 6, -2, -21, -23, 12, -11, -13, 17, 22, -1, 14, -25, -6, 18, 10, -12, -7, 40, 40, -18, -12, -23, -13, 15, -23, -6, 9, -14, -7, 16, 9, 2, -1, -3, 16, -22, -20, -9, 22, -7, 11, 8, -8, -21, 5, 14, -6, -1, 13, -21, -15, 6, 16, 
  -12, -7, -8, 5, 10, -21, -17, 5, 10, 6, 19, -27, -20, 20, -31, -17, -31, -5, 10, -24, 16, 25, -13, 16, -24, -14, -3, -23, 18, -8, 23, -17, -13, 14, -3, -17, -22, -1, 51, 17, -29, 17, -19, 23, 0, 19, 0, -13, -31, -11, -5, 12, 9, -4, -15, -11, 30, 0, 25, -14, 0, 10, -13, 26, 6, 26, 26, 19, 1, 20, 5, -12, 27, -1, 19, 73, -35, 11, 14, 18, 33, 8, -19, -8, 4, -26, 16, 3, -20, 5, -11, 12, 5, 23, -12, 9, 26, 26, 29, 30, -18, 28, -11, 28, -13, -2, 21, -17, 0, -6, -3, -19, 43, 31, -26, 15, 24, -22, 19, 19, -15, -2, -8, -22, -20, -26, -4, 21, 21, -16, -8, -12, 1, 0, 19, 14, 24, 11, -21, 19, -6, 11, -8, -12, 19, 18, 10, -13, -12, 21, 65, -26, 11, 12, 0, -19, -14, 13, -15, -23, 8, 12, 2, -7, -24, -14, 9, 4, 17, -14, 14, 14, -11, -12, -22, 13, 25, 11, 6, 14, -25, -18, -21, -1, 14, 
  0, 21, -19, -24, -24, 7, -3, 4, 9, 8, -2, 10, -14, 12, 12, 20, 4, 11, 9, 15, -23, 21, -21, 11, 6, 0, -11, -9, -5, -14, 7, -9, -9, 13, -2, 5, 0, -23, 6, 22, 15, -12, 7, -18, 18, -16, -23, -6, -18, 17, 10, -2, 18, 21, 10, -14, 22, 11, -18, 21, 1, -16, 5, -11, 4, 10, 4, -15, 2, 16, -22, 21, 20, 22, 10, 18, -11, 6, 21, 9, -18, -15, 3, 24, 25, 19, 2, 13, 14, 25, -1, 25, 5, 16, 24, 18, -21, 12, 13, 12, 19, 22, 24, -8, 17, -16, 4, 10, 25, -14, 8, -21, -25, 4, 15, -16, -9, -22, -1, -3, -14, 5, -3, -9, 9, -6, -15, -12, -7, -19, -5, -8, 5, 21, -17, -10, -14, -8, 3, 4, -13, 7, -10, -2, 21, 4, 24, 3, -2, -20, 12, -9, -10, 20, 15, 10, -12, 17, -13, -21, -14, 24, -20, 14, 2, -8, -22, 17, 16, 2, -5, -12, -14, -17, 14, 24, -3, -24, -22, -6, 25, -11, -17, -14, -7, 
  -29, 26, 13, -18, 2, -12, -15, -24, -1, -30, -28, -13, 1, 10, -11, 7, -22, -13, 7, -12, -21, -16, 11, -13, 9, -8, -7, 16, -19, 18, 6, -2, 17, -17, -8, -17, 8, -56, -22, 7, -2, 3, -21, -5, -21, -35, 10, -37, -17, -23, -11, -15, -20, -29, -14, -33, -16, -13, 5, -25, -26, 14, -23, -7, -25, 4, -7, -20, -9, 14, -28, -13, -20, 11, -15, 15, -21, 1, -15, 4, 2, 19, -28, -10, -3, 16, 0, -16, 24, -6, 4, 25, 24, 5, 5, -11, 4, -7, 24, -10, -2, -2, -3, -2, 24, 20, 14, 25, -3, -13, 16, 21, 50, -25, -31, 3, 4, 34, -3, -10, 24, 7, -5, 8, 34, 16, 8, -12, 34, 33, 6, 31, 7, 16, -7, 11, 28, -8, 34, -12, 31, 4, 25, 0, -2, 19, 34, 26, -16, -6, -14, -13, 10, 14, -1, -11, 14, 25, -14, -3, -19, 12, -1, 23, 22, -11, 25, -19, -2, 9, 15, -1, 15, 23, 14, -2, 16, 23, -20, 27, 23, -7, -18, 16, 28, 
  -5, 12, 23, 18, 18, -8, -10, 21, 9, -3, -9, 25, -9, 18, -18, -8, -18, 7, 23, -14, 14, -11, -19, 25, -14, -20, -13, 8, -2, -15, -3, -19, 1, 6, 2, 25, 24, -14, 18, -21, -24, -7, 25, -8, 8, -17, 2, 24, -19, 12, -12, -15, 23, 13, 7, -19, 19, -22, -6, -12, 8, -20, 12, 24, -5, 13, -3, 1, 8, -7, 19, -9, 16, 23, 12, 6, -20, -19, 19, -20, -20, -23, -22, 4, 13, 24, -10, 6, 6, 11, 0, 24, -23, -13, 18, 13, 11, -9, 23, -23, 22, 10, 2, -15, -14, -25, -20, 24, 7, -25, -23, -12, 20, 1, -17, 7, 17, 25, -13, -4, -15, 23, 6, 22, 1, 11, 12, 21, 24, 22, 13, 11, -15, 20, 2, -5, 24, 15, 5, -5, -25, -23, -23, 18, 13, 0, 7, 11, 22, -1, 12, 21, -25, -18, 7, -7, -5, 10, 10, -13, -20, -23, -25, -1, 21, 19, -22, -12, 21, 5, -25, -8, 18, 19, 19, 20, 5, 4, -9, 19, 25, 22, 23, -11, -22, 
  24, -41, 44, -27, -4, 13, -6, 7, 8, -4, -17, -4, -18, -12, -9, -3, 13, -4, -5, 16, -6, 26, -8, 25, -7, -17, 4, -3, -19, -14, 17, -6, -12, -18, 28, 22, 12, -9, -57, 10, -21, -3, -17, 4, -1, -4, 21, 7, -12, -15, 7, -12, 18, -11, 15, -21, -17, -14, -1, 25, -6, -12, -14, 21, 11, -12, 19, -21, 1, 22, 18, 12, 18, -13, -7, -67, 64, -9, -45, -6, -14, 3, 24, 6, 19, 13, 29, 8, 2, -20, -25, 16, 10, -15, -25, -27, 7, -2, 15, -22, -33, 17, -3, -7, -23, -8, -22, -28, -11, 0, -28, 21, -63, -36, -16, -25, 10, 10, -23, -25, 21, -17, 1, 13, 9, 32, -1, -8, 0, 2, -24, -14, -3, -5, -6, -19, 2, 21, -17, 3, 13, -12, -8, -15, 16, 15, 3, 1, 21, 2, -25, 11, 14, 12, 2, -8, 11, -14, 25, -3, 5, -13, 10, -24, -9, -18, -10, 25, -4, 10, 21, -18, 21, 15, -6, 10, -17, -14, 15, 13, 7, -11, -24, 20, 17, 
  48, 0, 23, -15, -9, -7, 8, -3, 14, 12, -21, 17, 11, 1, 4, -5, 6, -14, -11, 8, -6, -25, 21, -19, -2, 0, -18, -10, 10, 21, -16, 5, 22, -16, 1, 7, -21, 18, -49, 1, -15, -7, -15, -12, -18, -33, -41, -3, -5, -2, 2, 8, -26, 5, 3, -22, 3, -28, -19, 20, -21, 15, -23, 5, -26, -9, -12, -25, -25, -22, -31, 8, -16, -14, 5, -94, 26, -35, -37, -25, 2, -1, 10, -16, 11, 28, 39, 12, 18, 14, -15, 8, -19, -9, 4, -23, -18, -19, 21, -15, -9, 18, 16, -24, -10, 13, -27, -21, -11, 8, 20, 34, -41, -50, 1, -14, -5, -18, -10, -5, 27, 0, 22, 0, 12, 27, -16, 6, -10, 0, -18, -1, 18, 12, 1, 22, 9, 19, -15, -11, 7, -19, 7, 5, -2, 17, -19, 15, 30, 6, -72, 12, -12, 0, 19, -6, -8, 1, 11, 23, -13, -17, 29, 1, 15, -8, 22, 22, 27, -12, -4, 21, 12, -3, 8, 20, -13, 10, -9, -3, 12, -11, -2, 1, -11, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,185 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0067084012553095818, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.040334951132535934, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.048443756997585297, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,3 } };
const TfArray<1, float> quant9_scale = { 1, { 0.09841550886631012, } };
const TfArray<1, int> quant9_zero = { 1, { 8 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 185, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 30, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 3700, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 192), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1036761_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1036761_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1036761_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1036761_3_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1036761_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
